### ISSUE TITLE
✈️ Pilot March 22

### ISSUE THREAD

**Issue by JamesPHoughton** [willschulz/bad-influence#6]
- WBL will coordinate recruitment
- starts at 3:00pm

# Todos:

### Intro splash
- [x] If you finish the first part early
- [x] competitive bonus
- [x] WBL ID only
### consent
- [x] Mturk worker id => payment ID
### Treatment
- [x] fix the control condition
- [x] same total duration, move leader time to group time

**Comment by willschulz** [comment]
Additional points:
- remove “three” from the description of the discussion process
- revise the end instruction that states “Your discussion is now over”  To read, “Your discussion is now over, please proceed to the post-discussion survey.”

On Mar 22, 2023, at 11:35 AM, James Houghton ***@***.***> wrote:

﻿

Todos:

Change intros:

Intro splash

  *    If you finish the first part early
  *    competitive bonus
  *    WBL ID only

consent

  *    Mturk worker id => payment ID

We need to fix the control condition

  *   same total duration, move leader time to group time

**Comment by JamesPHoughton** [comment]
Experiment is updated and live with config:
```json
{
  "batchName": "WBL_Pilot_1",
  "useData": "true",
  "treatmentFile": "projects/bad_influence/treatments.policing.yaml",
  "dispatchWait": 3,
  "useTreatments": ["no_leader_assigned", "assigned_leader"],
  "useIntroSequence": "cross_party_match",
  "platformConsent": "US",
  "launchDate": "23 Mar 2023 15:00:00 EDT"
}
```
